// TOKEN AUTHENTICATION
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

// USER AUTHENTICATION

export const AUTHENTICATION_USER_START = 'AUTHENTICATION_USER_START';
export const AUTHENTICATION_USER_SUCCESS = 'AUTHENTICATION_USER_SUCCESS';
export const AUTHENTICATION_USER_FAIL = 'AUTHENTICATION_USER_FAIL';
export const AUTHENTICATION_USER_ERROR = 'AUTHENTICATION_USER_ERROR';
export const AUTHENTICATION_USER_RESET = 'AUTHENTICATION_USER_RESET';

export const SEARCH_USERS_START = 'SEARCH_USERS_START';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
export const SEARCH_USERS_NOT_FOUND = 'SEARCH_USERS_NOT_FOUND';
export const GET_USER_POPUP = 'GET_USER_POPUP';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const SAVE_USER_START = 'SAVE_USER_START';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';

export const USER_SUBSCRIPTION_START = 'USER_SUBSCRIPTION_START';
export const USER_SUBSCRIPTION_SUCCESS = 'USER_SUBSCRIPTION_SUCCESS';
export const USER_SUBSCRIPTION_FAIL = 'USER_SUBSCRIPTION_FAIL';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

// EMAIL SUBSCRIPTION

export const SUBSCRIPTION_EMAIL_START = 'SUBSCRIPTION_EMAIL_START';
export const SUBSCRIPTION_EMAIL_SUCCESS = 'SUBSCRIPTION_EMAIL_SUCCESS';
export const SUBSCRIPTION_EMAIL_FAIL = 'SUBSCRIPTION_EMAIL_FAIL';
export const SUBSCRIPTION_EMAIL_RESET_FLAG = 'SUBSCRIPTION_EMAIL_RESET_FLAG';

// EMAIL UPDATE
export const USER_UPDATES_START = 'USER_UPDATES_START';
export const USER_UPDATES_SUCCESS = 'USER_UPDATES_SUCCESS';
export const USER_UPDATES_FAIL = 'USER_UPDATES_FAIL';

// Dashboard ORDERS

export const ORDERS_BY_MONTH_START = 'ORDERS_BY_MONTH_START';
export const ORDERS_BY_MONTH_SUCCESS = 'ORDERS_BY_MONTH_SUCCESS';
export const ORDERS_BY_MONTH_FAIL = 'ORDERS_BY_MONTH_FAIL';
export const ORDERS_BY_MONTH_COUNT = 'ORDERS_BY_MONTH_COUNT';

export const ORDERS_NUMBERS_START = 'ORDERS_NUMBERS_START';
export const ORDERS_NUMBERS_SUCCESS = 'ORDERS_NUMBERS_SUCCESS';
export const ORDERS_NUMBERS_FAIL = 'ORDERS_NUMBERS_FAIL';


export const ORDERS_NOTIFICATION_START = 'ORDERS_NOTIFICATION_START';
export const ORDERS_NOTIFICATION_DATA = 'ORDERS_NOTIFICATION_DATA';
export const ORDERS_NOTIFICATION_INCREMENT = 'ORDERS_NOTIFICATION_INCREMENT';
export const ORDERS_NOTIFICATION_RESET_SIZE = 'ORDERS_NOTIFICATION_RESET_SIZE';
export const ORDERS_NOTIFICATION_FAIL = 'ORDERS_NOTIFICATION_FAIL';



// ORDERS

export const ORDER_BY_ID_START = 'ORDER_BY_ID_START';
export const ORDER_BY_ID_SUCCESS = 'ORDER_BY_ID_SUCCESS';
export const ORDER_BY_ID_FAIL = 'ORDER_BY_ID_FAIL';
export const ORDER_BY_ID_POPUP = 'ORDER_BY_ID_POPUP';

export const SAVE_ORDER_START = 'SAVE_ORDER_START';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAIL = 'SAVE_ORDER_FAIL';

export const SEARCH_ORDERS_START = 'SEARCH_ORDERS_START';
export const SEARCH_ORDERS_SUCCESS = 'SEARCH_ORDERS_SUCCESS';
export const SEARCH_ORDERS_BY_STATUS_SUCCESS = 'SEARCH_ORDERS_BY_STATUS_SUCCESS';
export const SEARCH_ORDERS_FAIL = 'SEARCH_ORDERS_FAIL';

// PRODUCTS

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';

export const PRODUCT_BY_ID_START = 'PRODUCT_BY_ID_START';
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS';
export const PRODUCT_BY_ID_FAIL = 'PRODUCT_BY_ID_FAIL';
export const PRODUCT_BY_ID_POPUP = 'PRODUCT_BY_ID_POPUP';

export const SAVE_PRODUCT_START = 'SAVE_PRODUCT_START';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAIL = 'SAVE_PRODUCT_FAIL';

export const BULK_PRODUCTS_START = 'BULK_PRODUCTS_START';
export const BULK_PRODUCTS_SUCCESS = 'BULK_PRODUCTS_SUCCESS';
export const BULK_PRODUCTS_FAIL = 'BULK_PRODUCTS_FAIL';
