// TOKEN AUTHENTICATION
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

// USER AUTHENTICATION

export const AUTHENTICATION_USER_START = 'AUTHENTICATION_USER_START';
export const AUTHENTICATION_USER_SUCCESS = 'AUTHENTICATION_USER_SUCCESS';
export const AUTHENTICATION_USER_FAIL = 'AUTHENTICATION_USER_FAIL';
export const AUTHENTICATION_USER_ERROR = 'AUTHENTICATION_USER_ERROR';
export const AUTHENTICATION_USER_RESET = 'AUTHENTICATION_USER_RESET';

export const SEARCH_USERS_START = 'SEARCH_USERS_START';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
export const SEARCH_USERS_NOT_FOUND = 'SEARCH_USERS_NOT_FOUND';
export const GET_USER_POPUP = 'GET_USER_POPUP';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const SAVE_USER_START = 'SAVE_USER_START';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';

// Dashboard ORDERS

export const ORDERS_BY_MONTH_START = 'ORDERS_BY_MONTH_START';
export const ORDERS_BY_MONTH_SUCCESS = 'ORDERS_BY_MONTH_SUCCESS';
export const ORDERS_BY_MONTH_FAIL = 'ORDERS_BY_MONTH_FAIL';

export const ORDERS_NUMBERS_START = 'ORDERS_NUMBERS_START';
export const ORDERS_NUMBERS_SUCCESS = 'ORDERS_NUMBERS_SUCCESS';
export const ORDERS_NUMBERS_FAIL = 'ORDERS_NUMBERS_FAIL';

// ORDERS

export const ORDER_BY_ID_START = 'ORDER_BY_ID_START';
export const ORDER_BY_ID_SUCCESS = 'ORDER_BY_ID_SUCCESS';
export const ORDER_BY_ID_FAIL = 'ORDER_BY_ID_FAIL';
export const ORDER_BY_ID_POPUP = 'ORDER_BY_ID_POPUP';

export const SAVE_ORDER_START = 'SAVE_ORDER_START';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAIL = 'SAVE_ORDER_FAIL';

export const SEARCH_ORDERS_START = 'SEARCH_ORDERS_START';
export const SEARCH_ORDERS_SUCCESS = 'SEARCH_ORDERS_SUCCESS';
export const SEARCH_ORDERS_FAIL = 'SEARCH_ORDERS_FAIL';

// PRODUCTS

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';

export const PRODUCT_BY_ID_START = 'PRODUCT_BY_ID_START';
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS';
export const PRODUCT_BY_ID_FAIL = 'PRODUCT_BY_ID_FAIL';
export const PRODUCT_BY_ID_POPUP = 'PRODUCT_BY_ID_POPUP';

export const SAVE_PRODUCT_START = 'SAVE_PRODUCT_START';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAIL = 'SAVE_PRODUCT_FAIL';

export const BULK_PRODUCTS_START = 'BULK_PRODUCTS_START';
export const BULK_PRODUCTS_SUCCESS = 'BULK_PRODUCTS_SUCCESS';
export const BULK_PRODUCTS_FAIL = 'BULK_PRODUCTS_FAIL';
