export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const AUTHENTICATION_USER_START = 'AUTHENTICATION_USER_START';
export const AUTHENTICATION_USER_SUCCESS = 'AUTHENTICATION_USER_SUCCESS';
export const AUTHENTICATION_USER_FAIL = 'AUTHENTICATION_USER_FAIL';
export const AUTHENTICATION_USER_ERROR = 'AUTHENTICATION_USER_ERROR';
export const AUTHENTICATION_USER_RESET = 'AUTHENTICATION_USER_RESET';