spring:
  application:
    name: search-product-service
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:8888}
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: INFO