export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_TYPE = 'LOAD_TYPE';
export const LOAD_SIZE = 'LOAD_SIZE';
export const LOAD_GENDER = 'LOAD_GENDER';


export const LOAD_PRODUCT_START = 'LOAD_PRODUCT_START';
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL';


export const ADD_PRODUCT_TO_ORDER = 'ADD_PRODUCT_TO_ORDER';
export const REMOVE_PRODUCT_TO_ORDER = 'REMOVE_PRODUCT_TO_ORDER';