apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
        collect_logs: "true"
    spec:
      containers:
        - name: api-gateway
          image: gcr.io/complete-tube-306819/api-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi


---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    collect_logs: "true"
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30042
