apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
        collect_logs: "true"
    spec:
      containers:
        - name: auth-service
          image: gcr.io/complete-tube-306819/auth-service:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              port: 9292
              path: /health/live
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              port: 9292
              path: /health/ready
          resources:
            limits:
              memory: 456Mi
            requests:
              cpu: 100m
              memory: 128Mi


---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    collect_logs: "true"
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8080
      targetPort: 9292