server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO:https://github.com/sifraden/config.git}
          clone-on-start: true
          skipSslValidation: true
          force-pull: true
        accept-empty: false
      encrypt:
        enabled: true
#      discovery:
#        enabled: true
 #   bus:
 #     enabled: true
 # rabbitmq:
 #   host: ${RABBITMQ_SERVER:rabbitmq}
 #   port: 5672
 #   username: guest
 #   password: guest




