server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO:https://github.com/sifraden/config.git}
          clone-on-start: true
          skipSslValidation: true
          force-pull: true
        accept-empty: false
      encrypt:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"




