server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO:https://github.com/sifraden/config.git}
          clone-on-start: true
          skipSslValidation: true
          force-pull: true
        accept-empty: false
      encrypt:
        enabled: true

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true




