server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sifraden/config.git
          clone-on-start: true
      encrypt:
        enabled: true
      discovery:
        enabled: true
    bus:
      enabled: true
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 30

